DropdownAlert.js, README.md
thank you for this cool library. 
Predefined colors do not match my design style guide, so I added an option to configure them.
=> configurable colors

DropdownAlert.js
Fix Code not respecting that styles arent always objects #45
=> Flatten prop styles;

.gitignore, DropdownAlert.js, README.md
Implement if statusBar styles are updated; #56
=> Add prop updateStatusBar

DropdownAlert.js, package.json
related to https://github.com/testshallpass/react-native-dropdownalert/issues/52
=> use prop-types package

DropdownAlert.js, Example/DropdownAlert.js
=> Update useNativeDriver iOS only

DropdownAlert.js, __tests__/__snapshots__/DropdownAlert-test.js.snap
Fixes https://github.com/testshallpass/react-native-dropdownalert/issues/70
=> Add elevation props

DropdownAlert.js, __tests__/__snapshots__/DropdownAlert-test.js.snap, constants.js, functions.js, imageview.js, label.js
- Smaller components
- Add shared constants and functions utils
- Reduce methods
- Prettier format
=> Infra fixes

DropdownAlert.js, README.md
Basically exposed inner containers as props to allow access to control `paddingTop` for predefined types
=> Add default containers props; Update Readme

DropdownAlert.js, README.md, __tests__/DropdownAlert-test.js, __tests__/__snapshots__/DropdownAlert-test.js.snap
I had some issues with trying to get the dropdownalert to appear in front of a header I've got set to a specific zIndex for animation and transition reasons. I tried changing the styles for container but that View is too far down in the DOM to have an effect on zIndex.
=> Added prop to specify zIndex on container

DropdownAlert.js, __tests__/__snapshots__/DropdownAlert-test.js.snap, package-lock.json, package.json
If showCancel was set to true, tapping the notification would not call onClose prop and do nothing. Now, it is based on tapToCloseEnabled, which makes sense.
=> Fixed issue for tapToCloseEnabled and showCancel

DropdownAlert.js, README.md, __tests__/__snapshots__/DropdownAlert-test.js.snap, package-lock.json
Fix the spacing for iPhone X. 
When I tested it didn't see any difference on other iPhone models or Android (where that view is a no-op)
=> Add iPhone X Support

DropdownAlert.js, README.md
If the render prop is present it will take over to render the element(s) how you see fit. Addresses:  #106
=> Provide render functions to allow more customization

DropdownAlert.js, README.md
Allow users to decide to disable or not native driver for animations.
=> Add useNativeDriver prop

DropdownAlert.js, README.md
Addresses: Custom image per alert type #120
=> Allow custom images for alert types

DropdownAlert.js
Based on message's size and it's content, maybe we want to change default closeInterval. So I've added it's functionality to alertWithType function to handle it's interval.
=> Added closeInterval handling for alertWithType function

DropdownAlert.js, README.md, __tests__/__snapshots__/DropdownAlert-test.js.snap
This allows for React Native Web support as it is now possible to set `position: fixed`
=> allow overrides of the wrapperStyle

DropdownAlert.js, __tests__/DropdownAlert-test.js
=> Fix "Set replaceEnabled to false, alert won't show up"

DropdownAlert.js
=> Android: Status bar colour change delay on close

README.md
* Document caveats: Stack Navigator #73
=> update readme with caveats

DropdownAlert.js
Hi,
Thank you for your package. 
I missed the state to know the type of an alert to be able to choose which kind of custom image I need.
Regards,
Xavier
=> Add this.state to renderImage props

DropdownAlert.js, README.md, __tests__/__snapshots__/DropdownAlert-test.js.snap
=> Add accessible, accessibilityLabel and testID props

DropdownAlert.js, functions.js
=> Bugfix title message not passed

DropdownAlert.js, index.d.ts
This fixes the issue https://github.com/testshallpass/react-native-dropdownalert/issues/177.
=> Added payload to alertWithType() passed down to onClose()

DropdownAlert.js
Fixes #169 StatusBar backgroundColor doesn't go to its default value when moving between screens
=> Fix status bar background color android

DropdownAlert.js, Example/App.js, Example/constants.js, Example/package-lock.json, Example/package.json, README.md, __tests__/CancelButton-test.js, __tests__/DropdownAlert-test.js, docs/PROPS.md
* Rework onTap prop. PR #180 Please review @rydecars
* Rework payload image source. PR #175 and related to #161 Please review @lk321
=> onTap prop and payload image source

DropdownAlert.js
=> move cancel button into safe area view

index.d.ts
Fixes `state` type on `render` prop params
=> Fix render state type
